"""Evidence modes, decision tracks, and the separation between them.

Every gate is evaluated twice. The **REHEARSAL** track proves the promotion
machinery works — that gates fire, evidence binds, signatures verify, incidents
reset counters. The **REAL** track governs whether the bank has actually
authorised anything. Both are useful; conflating them would be a
misrepresentation, because a rehearsal that passes every gate demonstrates
exactly nothing about bank authorisation.

The separation is enforced at three levels, deliberately redundant:

1. **Type** — a :class:`DecisionTrack` is not a boolean, so it cannot be
   silently inverted by a falsy value.
2. **Mode admissibility** — :func:`admits_track` refuses synthetic evidence on
   the real track. There is no flag to override it.
3. **Signature** — the trust registry binds each key to the modes it may sign
   (workstream 3). A rehearsal key signing ``REAL_BANK`` fails verification.

Layer 3 is the one that matters when the other two are bypassed, which is why
mode is carried inside the signed payload rather than alongside it: tampering
with the mode invalidates the signature.
"""

from __future__ import annotations

from enum import Enum
from typing import FrozenSet, Mapping, Tuple

EVIDENCE_MODE_POLICY_VERSION = "v32-evidence-mode-policy-1.0.0"


class DecisionTrack(str, Enum):
    """Which question a gate evaluation answers."""

    #: Governs actual bank authorisation. Only real evidence is admissible.
    REAL = "REAL"
    #: Proves the machinery works. Synthetic evidence is expected here.
    REHEARSAL = "REHEARSAL"


TRACKS: Tuple[DecisionTrack, ...] = tuple(DecisionTrack)


class PromotionEvidenceMode(str, Enum):
    """Where a piece of evidence came from, ordered by authority."""

    #: A required artifact or attestation does not exist. Absence is recorded,
    #: never silently omitted from the gate register.
    NOT_AVAILABLE = "NOT_AVAILABLE"
    #: Generated by a simulation laboratory in this repository. Proves the
    #: machinery; proves nothing about the bank.
    SYNTHETIC_REHEARSAL = "SYNTHETIC_REHEARSAL"
    #: Representative economics, feasibility or governance policy. It can
    #: exercise the mechanism in rehearsal but carries no bank authority.
    SIMULATED_POLICY = "SIMULATED_POLICY"
    #: Approved public evidence. It is admissible only where a gate explicitly
    #: permits public evidence and never substitutes for E3 or bank attestation.
    PUBLIC_APPROVED = "PUBLIC_APPROVED"
    #: Real, verifiable, and public — a signed container image, an SBOM, a
    #: published regulatory filing. Not bank-internal, but not simulated.
    PUBLIC_PACKAGE = "PUBLIC_PACKAGE"
    #: Produced from real bank systems or data, but not yet attested by an
    #: accountable bank function.
    REAL_BANK = "REAL_BANK"
    #: Real bank evidence carrying a named accountable approver's attestation.
    BANK_ATTESTED = "BANK_ATTESTED"


#: Authority ordering. A gate declaring a minimum mode accepts that mode or any
#: stronger one. ``SYNTHETIC_REHEARSAL`` sits at 0 because it contributes no
#: bank authority at all — see ``bank_evidence_weight``.
MODE_AUTHORITY: Mapping[PromotionEvidenceMode, int] = {
    PromotionEvidenceMode.NOT_AVAILABLE: -2,
    PromotionEvidenceMode.SYNTHETIC_REHEARSAL: 0,
    PromotionEvidenceMode.SIMULATED_POLICY: 0,
    PromotionEvidenceMode.PUBLIC_APPROVED: 1,
    PromotionEvidenceMode.PUBLIC_PACKAGE: 1,
    PromotionEvidenceMode.REAL_BANK: 2,
    PromotionEvidenceMode.BANK_ATTESTED: 3,
}

EVIDENCE_MODES: Tuple[PromotionEvidenceMode, ...] = tuple(PromotionEvidenceMode)

#: Modes that may appear on the REAL track. Synthetic is absent by construction,
#: not by a runtime check that could be skipped.
REAL_TRACK_MODES: FrozenSet[PromotionEvidenceMode] = frozenset(
    {
        PromotionEvidenceMode.PUBLIC_APPROVED,
        PromotionEvidenceMode.PUBLIC_PACKAGE,
        PromotionEvidenceMode.REAL_BANK,
        PromotionEvidenceMode.BANK_ATTESTED,
    }
)

#: Modes that may appear on the REHEARSAL track — all of them. Real evidence is
#: admissible in a rehearsal; the reverse is what is forbidden. Rehearsing with
#: real artifacts where they exist makes the rehearsal stronger, not weaker.
REHEARSAL_TRACK_MODES: FrozenSet[PromotionEvidenceMode] = frozenset(
    mode for mode in EVIDENCE_MODES if mode is not PromotionEvidenceMode.NOT_AVAILABLE
)

TRACK_ADMISSIBLE_MODES: Mapping[DecisionTrack, FrozenSet[PromotionEvidenceMode]] = {
    DecisionTrack.REAL: REAL_TRACK_MODES,
    DecisionTrack.REHEARSAL: REHEARSAL_TRACK_MODES,
}


def admits_track(mode: PromotionEvidenceMode, track: DecisionTrack) -> bool:
    """Whether evidence of this mode may be used on this track."""
    return mode in TRACK_ADMISSIBLE_MODES[track]


def is_synthetic(mode: PromotionEvidenceMode) -> bool:
    return mode in {
        PromotionEvidenceMode.SYNTHETIC_REHEARSAL,
        PromotionEvidenceMode.SIMULATED_POLICY,
    }


def satisfies_minimum(
    mode: PromotionEvidenceMode, minimum: PromotionEvidenceMode
) -> bool:
    """Whether ``mode`` carries at least the authority ``minimum`` demands."""
    return MODE_AUTHORITY[mode] >= MODE_AUTHORITY[minimum]


def bank_evidence_weight(mode: PromotionEvidenceMode) -> float:
    """The fraction of a gate's severity weight this mode contributes to BER.

    Synthetic evidence contributes **zero**. This is the single most important
    number in the scoring model: it is what stops a fully-rehearsed system from
    reporting a high Bank Evidence Readiness score and reading as nearly
    production-ready when no bank evidence exists at all.

    Public artifacts contribute partially — a signed image is genuine evidence
    about the supply chain, but it is not a bank attestation and should not
    score as one.
    """
    return {
        PromotionEvidenceMode.NOT_AVAILABLE: 0.0,
        PromotionEvidenceMode.SYNTHETIC_REHEARSAL: 0.0,
        PromotionEvidenceMode.SIMULATED_POLICY: 0.0,
        PromotionEvidenceMode.PUBLIC_APPROVED: 1.0,
        PromotionEvidenceMode.PUBLIC_PACKAGE: 1.0,
        PromotionEvidenceMode.REAL_BANK: 1.0,
        PromotionEvidenceMode.BANK_ATTESTED: 1.0,
    }[mode]


def track_admission_reason(
    mode: PromotionEvidenceMode, track: DecisionTrack
) -> str:
    """A stable reason code for an admission decision, admitted or not."""
    if admits_track(mode, track):
        return f"ADMITTED_{mode.value}_ON_{track.value}"
    if mode is PromotionEvidenceMode.SYNTHETIC_REHEARSAL:
        return f"REFUSED_SYNTHETIC_EVIDENCE_ON_{track.value}_TRACK"
    return f"REFUSED_{mode.value}_EVIDENCE_ON_{track.value}_TRACK"
